governor_little=auto
conservative=1
adj_min_power=6.0
fast_down_always=1
adj_min_bat_temp=38.0
fas_engine=feas|fas|fas_lite
adj_max_power=9.0
adj_max_bat_temp=45.0
governor_middle=auto
variance_adjust=1
# scheme=sweet_bal (日常均衡)
margin_offset=300
download_detect=0
target_fps_offset=0
adj_max_soc_temp=88.0
status_notify=0
adj_min_soc_temp=65.0
governor_prime=auto
